name: building_damage_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - black
  - build
  - duckdb
  - duckdb-cli
  - click
  - pre-commit
  - flake8
  - requests
  - setuptools
