[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "building_damage"
version = "0.1.0"

[tool.black]
line-length = 79

[tool.setuptools]
package-dir = {"" = "src"}